---
title       : PACE App
subtitle    : Real Statistical Process Control
author      : George Miranda
job         : Data Scientist
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
transition  : rotate
ext_widgets : {rCharts: [libraries/nvd3]}
--- 

## PACE

_What if you were able to predict the number of employees you will need to do a particular job?_

_What if you had the insight to know which business processes were under-performing?_

In the never ending struggle to make better business decisions, the PACE app has been developed for everyone involved in a business setting to observe historical trends and calculate staffing needs based on current performance.

As a manager for Los Angeles County, you will be able to predict staffing needs based on trends and sophisticated algorithms. Even front line staff will be empowered to see their impact on the performance of processes. The openness of this data will bring to light which operations require a "tune-up", or process improvement. The PACE app is __business__ __intelligence__ customized for you.

--- 

## How It Works

The app relies on the following set of R packages:
* data.table
* ggplot2
  
  
It uses a dataset that includes information on individual employee performance. The data is aggregated to show overall trends and patterns, but still uses individual data points to inform the predictive algorithms.

No knowledge of programming or ability to code is necessary in order to use this app. All the data and packages are already loaded onto the app. Datasets are updated on a nightly basis to provide up to date information. 

---

## How It Works

Start by simply clicking the link below.  

http://georgemirandajr.shinyapps.io/pace/
  
Then choose either the Recorder or Elections operation to view data on their specific tasks. The primary Recorder task is "indexing", which is the act of an employee entering information found in property documents into a database. The primary Elections task is "voter registration", which is the act of an employee entering information found on a voter registration form into a database. 

You can then select a date range to explore general data patterns using the widget found on the left sidebar panel. You can also enter the number of expected documents that need processing in the "predict staff" widget to estimate the number of staff needed to complete that many documents. 

---

## Return on Investment

Invest in the right things at the right time. The chart below shows the percentage gained in dollars for the type of business activity investment.

```{r echo=FALSE, results='asis'}
library(rCharts)

roi <- read.csv("C:/Users/Geo/Documents/dataproducts/first_deck/roi.csv",header = TRUE)
n1 <- nPlot(roi ~ activity, group = 'type', data = roi, type = 'multiBarChart')
n1$print('chart1')

```


--- &radio
  
## Hard Choices

What will you choose to do with the volumes of data at your disposal?

1. Dispose of it

2. Flip through it every once in a while

3. Have somebody else analyze it and trust their interpretations 

4. _Use it as a guide to do the right things_

*** .hint 
Hint: It's not useful if it just sits there.

*** .explanation 
Answer: The best answer is to use it as a guide toward doing the right things. The PACE app will allow you to manipulate data and answer questions you never thought would be this easy to answer.


